version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: hr-portal-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: portal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./server/userSeed.js:/docker-entrypoint-initdb.d/userSeed.js:ro
    networks:
      - hr-portal-network

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr-portal-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/portal?authSource=admin
      - JWT_SECRET=your-super-secure-jwt-secret-key-here
      - CLIENT_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASS=your-app-password
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
    depends_on:
      - mongodb
    volumes:
      - ./server/public/uploads:/app/public/uploads
    networks:
      - hr-portal-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: hr-portal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - hr-portal-network

volumes:
  mongodb_data:
    driver: local

networks:
  hr-portal-network:
    driver: bridge