services:
  # Backend API Service
  - type: web
    name: hr-portal-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      # hello
  # Frontend Static Site
  - type: static
    name: hr-portal-frontend
    buildCommand: npm run client:install && npm run client:build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        sync: false

# Database (MongoDB Atlas recommended)
databases:
  # Note: Render's free PostgreSQL can be used, but MongoDB Atlas is recommended
  # for this MERN stack application. Configure MongoDB Atlas separately.